# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Build / test 

on:
  push:

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      API_URL: ${{ secrets.API_URL }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
      - run: yarn --prefer-offline
      - run: yarn lint
      - run: yarn prettier
      - run: yarn test
      - run: yarn build